<?php

namespace Proxies;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class SensioHelloBundleDocumentUserProxy extends \Sensio\HelloBundle\Document\User implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $documentPersister;
    private $identifier;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->documentPersister = $documentPersister;
        $this->identifier = $identifier;
    }
    private function __load()
    {
        if (!$this->__isInitialized__ && $this->documentPersister) {
            $this->__isInitialized__ = true;
            if ($this->documentPersister->load($this->identifier, $this) === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->identifier);
            }
            unset($this->documentPersister, $this->identifier);
        }
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getAge()
    {
        $this->__load();
        return parent::getAge();
    }

    public function setAge($age)
    {
        $this->__load();
        return parent::setAge($age);
    }

    public function getJob()
    {
        $this->__load();
        return parent::getJob();
    }

    public function setJob($job)
    {
        $this->__load();
        return parent::setJob($job);
    }


    public function __sleep()
    {
        return array('id', 'login', 'slug', 'firstname', 'lastname', 'email', 'age', 'job');
    }
}